"""add_late_to_status_enum

Revision ID: 055ce72e36bb
Revises: 5acec2cb5f0f
Create Date: 2026-05-04 03:09:06.137472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055ce72e36bb'
down_revision: Union[str, Sequence[str], None] = '5acec2cb5f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
