"""add new tables in Task model

Revision ID: 5acec2cb5f0f
Revises: f55951ecc038
Create Date: 2026-03-31 20:39:51.713443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acec2cb5f0f'
down_revision: Union[str, Sequence[str], None] = 'f55951ecc038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_recurrences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_reset_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_reset_date')
        batch_op.drop_column('recurrence_count')
        batch_op.drop_column('max_recurrences')
        batch_op.drop_column('recurrence_interval_days')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
