"""add goal recurrence, cycle log and task completion log

Revision ID: c48b3a1f2a54
Revises: 0093acb8d771
Create Date: 2026-09-19 23:16:16.529039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48b3a1f2a54'
down_revision: Union[str, Sequence[str], None] = '0093acb8d771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_cycle_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cycle_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('achieved_count', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cycle_start_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('cycle_start_date')
        batch_op.drop_column('recurrence_target')
        batch_op.drop_column('recurrence_interval_days')
        batch_op.drop_column('is_recurring')

    op.drop_table('task_completions')
    op.drop_table('goal_cycle_logs')
    # ### end Alembic commands ###
